version: "3.9"
services:
  uwsgi:
    image: python:3.8.13
    ports:
      - "8000:8080"
    volumes:
      - ./app:/app
      - ./uwsgi:/uwsgi
    working_dir: /app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - APPLICATION_MODULE=main:application
    entrypoint: ["/uwsgi/entrypoint.sh"]
  nginx:
    image: nginx:1.20.2
    ports:
      - "9000:80"
    volumes:
      - ./nginx/entrypoint.sh:/nginx/entrypoint.sh
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
      - ./uwsgi/uwsgi_params:/uwsgi/uwsgi_params
    entrypoint: ["/nginx/entrypoint.sh"]
